### ISSUE TITLE
Cannot reconcile data between tabs

### ISSUE THREAD

**Issue by SharmaA10** [jinshen1983/hilites.today#7]
I am unable to reconcile data between "Chart" tab and "Query".

For example, lets say within the Charts tab, I goto FY22/LIN _SC and look at a 485 approvals for receipt notice range 2208750000-2208754999. This page shows that 20 have been approved so far. 

If I then try to Query the same ranges and view last update - I only see 3 or 4 approved. 

Am I doing something wrong or is this a bug?

**Comment by jinshen-cn** [comment]
The query page is searching on USCIS in real-time. There is a trick here. Once USCIS approves a case, there is no case type on the status page anymore. that's why you see only a few cases on the search page.

There could be an enhancement to do. I can do a case lookup from the crawled dataset to backfill those missing case types.

See this for an example
https://egov.uscis.gov/casestatus/mycasestatus.do?appReceiptNum=LIN2190210901

**Comment by SharmaA10** [comment]
Got it, this makes sense. I think you have the right solution in mind. Thank you for looking into this!

**Comment by jinshen-cn** [comment]
I deployed a fix to this. it may fix 99% data discrepancy. But it's hard to 100% guarantee.

**Comment by SharmaA10** [comment]
Outstanding, thank you!
